### ISSUE TITLE
Compatibility with python3 

### ISSUE THREAD

**Issue by gnebbia** [philipperemy/Reuters-full-data-set#2]
Although in the README.md there is written to launch it with python3, I found problems,
in the read/write of the serialized files.
In particular when I try to launch "python3 read.py" I get strange characters, and moreover
when I try to generate my own dataset I get the following trace:
Traceback (most recent call last):
  File "dump_to_csv.py", line 38, in <module>
    read(sys.argv[1])
  File "dump_to_csv.py", line 15, in read
    data = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 8: ordinal not in range(128)

When tried with python2, it work without any problems.

**Comment by philipperemy** [comment]
Fixed in https://github.com/philipperemy/Reuters-full-data-set/commit/60b5390f16931c04f54a17a3095e88a6e8ede7b3

@gnebbia thanks for the great work!
